### ISSUE TITLE
[shaped-scripts] monster format needs converting

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#11]
After creating a valid JSON using the data on Mark's github, it fails to import any monster, generating the following error:

"ShapedScripts 1458693779315 ERROR : TypeError: Cannot call method 'substring' of undefined\n    at TrackedObj._validateAttrs (eval at <anonymous> (/home/symbly/www/d20-api-server/sandcastle/lib/sandbox.js:77:28), <anonymous>:544:22)\n    at createObj (eval at <anonymous> (/home/symbly/www/d20-api-server/sandcastle/lib/sandbox.js:77:28), <anonymous>:1356:23)\n    at Object.module.exports.createObj (evalmachine.<anonymous>:17797:12)\n    at Object.shapedModule.createNewCharacter (evalmachine.<anonymous>:19220:29)\n    at evalmachine.<anonymous>:19185:12\n    at Function._.each._.forEach (/home/symbly/www/d20-api-server/sandcastle/node_modules/underscore/underscore.js:153:9)\n    at Object.shapedModule.importMonstersFromJson (evalmachine.<anonymous>:19184:8)\n    at Command.handle (evalmachine.<anonymous>:19789:9)\n    at Object.processCommand (evalmachine.<anonymous>:19872:11)\n    at Object.shapedModule.handleInput (evalmachine.<anonymous>:19129:24)"

I don't know with certainty, but comparing your JSON examples on your github vs. Marks, the ability scores are stored very differently, though I can't say with certainty that this is the problem, will try to troubleshoot a bit more to be sure.

**Comment by symposion** [comment]
D'oh. The perils of releasing stuff in a hurry. Mark and I agreed a slightly updated format of the monster json to more closely match the compendium format. I've written the importer against that but I never got round to converting Mark's old JSON file. It should be relatively trivial but as I mentioned, unfortunately I have no time for the next few days.

I will probably add a version number to the JSON and build the converter into the script so that it's seamless for people with the old data.

**Comment by symposion** [comment]
Ok, this is fixed now, you'll need the latest js files from Mark's github and the latest script
