### ISSUE TITLE
[shaped-scripts] spell import casting time

### ISSUE THREAD

**Issue by beeke01** [symposion/roll20-api-scripts#14]
There is an inconsistency with the casting time field based on how spells are imported (via the script vs. imported via compendium).  For example a 1 action spell imported via the script has a casting time of "action"; the same spell from the compendium has "1 action".  It is also the case with bonus actions and reactions.

This wouldn't be a big deal except it will break the sheets ability to filter based on the action types.  I am not sure this is more of a sheet issue or an importer issue though tbh...

**Comment by symposion** [comment]
I think this is an issue with the data, to be honest - the value is just being pulled straight from the JSON and I see no reason for it to be different to the way it's expressed in the compendium. Rather than putting another transformer into the script I'm inclined to change the data to match the compendium and then get people to copy the data over again. I'll talk to Mark about changing it when I have some time.

**Comment by symposion** [comment]
Ok, this is fixed with the latest version of the data from Mark's github and the latest script. Let me know if you have any more problems
